### ISSUE TITLE
Proposal: recommend `nodemon` for watching and recompiling changes

### ISSUE THREAD

**Issue by opdavies** [rst2pdf/rst2pdf.github.io#28]
Something that I was wondering about was automatically re-compiling a PDF file when something in the RST or style file changes. It was also asked at the end of [Lorna's FOSDEM 2019 talk](https://youtu.be/WbsJsQk0td0?t=1475). The suggestion there was to use a Vim plugin, but that wouldn't be ideal for non-Vim users.

A solution that I've used before is [nodemon](https://nodemon.io) which can watch files and execute a command, and avoid the need to write Bash code. For example:

    nodemon --watch *.style --watch slides.rst --exec rst2pdf slides.rst

This would re-compile the PDF if a `.style` file or `slides.rst` changed.

If this recommendation would be OK, is there a particular place that I could add it to the docs? I was thinking within the "Tips, Tricks and Tools" section?

**Comment by lornajane** [comment]
Yes please! Start a new subsection for tools we use while building? I think either @akrabat or I should share our makefile as well. Great idea!
